import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ReactQueryProvider } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gumisofts — Beyond software we build sucess",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/gumicrop.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar appears on every page */}
        <div className="flex flex-col min-h-screen">
          {/* Navbar always at the top */}
          <ReactQueryProvider>
            <Navbar />
            {/* Main content area fills the available space */}
            <main className="flex-1">{children}</main>
            {/* Footer always at the bottom */}
            <Footer />
          </ReactQueryProvider>
        </div>
      </body>
    </html>
  );
}
